services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: yoyomut_frontend
    container_name: yoyomut_frontend
    ports:
      - 19278:8501
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ../YoyoMut_data:/app/dynamic_data 
    restart: unless-stopped
